//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Erase all logs
type MessageLogErase = common.MessageLogErase
