//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// EFI status output
type MessageEfiStatus = common.MessageEfiStatus
