//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Airspeed information from a sensor.
type MessageAirspeed = common.MessageAirspeed
