//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Response from a PARAM_EXT_SET message.
type MessageParamExtAck = common.MessageParamExtAck
