//autogenerated:yes
//nolint:revive
package csairlink_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/aircast-one/gomavlib/v4/pkg/dialect"
	dialectpkg "github.com/aircast-one/gomavlib/v4/pkg/dialects/csairlink"
)

func TestDialect(t *testing.T) {
	d := &dialect.ReadWriter{Dialect: dialectpkg.Dialect}
	err := d.Initialize()
	require.NoError(t, err)
}
