//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Vibration levels and accelerometer clipping
type MessageVibration = common.MessageVibration
