//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// The raw values of the actuator outputs (e.g. on Pixhawk, from MAIN, AUX ports). This message supersedes SERVO_OUTPUT_RAW.
type MessageActuatorOutputStatus = common.MessageActuatorOutputStatus
