//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Orientation of a mount
type MessageMountOrientation = common.MessageMountOrientation
