//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Global position estimate from a Vicon motion system source.
type MessageViconPositionEstimate = common.MessageViconPositionEstimate
