//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Play vehicle tone/tune (buzzer). Supported tunes can be determined using SUPPORTED_TUNES. Supersedes message PLAY_TUNE.
type MessagePlayTuneV2 = common.MessagePlayTuneV2
