//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Distance sensor information for an onboard rangefinder.
type MessageDistanceSensor = common.MessageDistanceSensor
