//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Camera tracking status, sent while in active tracking. Use MAV_CMD_SET_MESSAGE_INTERVAL to define message interval.
type MessageCameraTrackingImageStatus = common.MessageCameraTrackingImageStatus
