//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Setpoint in roll, pitch, yaw and thrust from the operator
type MessageManualSetpoint = common.MessageManualSetpoint
