//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Temperature and humidity from hygrometer.
type MessageHygrometerSensor = common.MessageHygrometerSensor
