//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Metrics typically displayed on a HUD for fixed wing aircraft.
type MessageVfrHud = common.MessageVfrHud
