//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Sent from autopilot to simulation. Hardware in the loop control outputs. Alternative to HIL_ACTUATOR_CONTROLS.
type MessageHilControls = common.MessageHilControls
