//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Request a data stream.
type MessageRequestDataStream = common.MessageRequestDataStream
