//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// The IMU readings in SI units in NED body frame
type MessageHilSensor = common.MessageHilSensor
