//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Data stream status information.
type MessageDataStream = common.MessageDataStream
