//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Report status of a command. Includes feedback whether the command was executed. The command microservice is documented at https://mavlink.io/en/services/command.html
type MessageCommandAck = common.MessageCommandAck
