//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Distance sensor information for an onboard rangefinder.
type MessageDistanceSensor = common.MessageDistanceSensor
