//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// The location and information of an AIS vessel
type MessageAisVessel = common.MessageAisVessel
