//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Speed estimate from a vision source.
type MessageVisionSpeedEstimate = common.MessageVisionSpeedEstimate
