//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// The current system altitude.
type MessageAltitude = common.MessageAltitude
