//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Information about a high level gimbal manager. This message should be requested by a ground station using MAV_CMD_REQUEST_MESSAGE.
type MessageGimbalManagerInformation = common.MessageGimbalManagerInformation
