//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Hardware status sent by an onboard computer.
type MessageOnboardComputerStatus = common.MessageOnboardComputerStatus
