//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// To debug something using a named 3D vector.
type MessageDebugVect = common.MessageDebugVect
