//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Current motion information from a designated system
type MessageFollowTarget = common.MessageFollowTarget
