//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// The IMU readings in SI units in NED body frame
type MessageHighresImu = common.MessageHighresImu
