//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Component information message, which may be requested using MAV_CMD_REQUEST_MESSAGE.
type MessageComponentInformation = common.MessageComponentInformation
