//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Stop log transfer and resume normal logging
type MessageLogRequestEnd = common.MessageLogRequestEnd
