//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Request a chunk of a log
type MessageLogRequestData = common.MessageLogRequestData
