//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Motion capture attitude and position
type MessageAttPosMocap = common.MessageAttPosMocap
