//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Message implementing parts of the V2 payload specs in V1 frames for transitional support.
type MessageV2Extension = common.MessageV2Extension
