//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Illuminator status
type MessageIlluminatorStatus = common.MessageIlluminatorStatus
