//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// The state of the navigation and position controller.
type MessageNavControllerOutput = common.MessageNavControllerOutput
