//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Delete all mission items at once.
type MessageMissionClearAll = common.MessageMissionClearAll
