//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// A message containing logged data (see also MAV_CMD_LOGGING_START)
type MessageLoggingData = common.MessageLoggingData
