//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Status of the Iridium SBD link.
type MessageIsbdLinkStatus = common.MessageIsbdLinkStatus
