//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Telemetry of power generation system. Alternator or mechanical generator.
type MessageGeneratorStatus = common.MessageGeneratorStatus
