//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// RTCM message for injecting into the onboard GPS (used for DGPS)
type MessageGpsRtcmData = common.MessageGpsRtcmData
