//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Set the vehicle attitude and body angular rates.
type MessageSetActuatorControlTarget = common.MessageSetActuatorControlTarget
