//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Current motion information from a designated system
type MessageFollowTarget = common.MessageFollowTarget
