//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Report button state change.
type MessageButtonChange = common.MessageButtonChange
