//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// The location of a landing target. See: https://mavlink.io/en/services/landing_target.html
type MessageLandingTarget = common.MessageLandingTarget
