//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Camera-IMU triggering and synchronisation message.
type MessageCameraTrigger = common.MessageCameraTrigger
