//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Stop log transfer and resume normal logging
type MessageLogRequestEnd = common.MessageLogRequestEnd
