//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Control vehicle tone generation (buzzer).
type MessagePlayTune = common.MessagePlayTune
