//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/csairlink"
)

// Response to the authorization request
type MessageAirlinkAuthResponse = csairlink.MessageAirlinkAuthResponse
