//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Accept / deny control of this MAV
type MessageChangeOperatorControlAck = common.MessageChangeOperatorControlAck
