//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/uavionix"
)

// Status message with information from UCP Heartbeat and Status messages.
type MessageUavionixAdsbOutStatus = uavionix.MessageUavionixAdsbOutStatus
