//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/icarous"
)

// ICAROUS heartbeat
type MessageIcarousHeartbeat = icarous.MessageIcarousHeartbeat
