//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/uavionix"
)

// Control message with all data sent in UCP control message.
type MessageUavionixAdsbOutControl = uavionix.MessageUavionixAdsbOutControl
