//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Power supply status
type MessagePowerStatus = common.MessagePowerStatus
