//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Reply to LOG_REQUEST_LIST
type MessageLogEntry = common.MessageLogEntry
