//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// The location and information of an AIS vessel
type MessageAisVessel = common.MessageAisVessel
