//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Barometer readings for 2nd barometer
type MessageScaledPressure2 = common.MessageScaledPressure2
