//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Motion capture attitude and position
type MessageAttPosMocap = common.MessageAttPosMocap
