//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Message appropriate for high latency connections like Iridium
type MessageHighLatency = common.MessageHighLatency
