//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Set the vehicle attitude and body angular rates.
type MessageSetActuatorControlTarget = common.MessageSetActuatorControlTarget
