//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// The autopilot is requesting a resource (file, binary, other type of data)
type MessageResourceRequest = common.MessageResourceRequest
