//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Illuminator status
type MessageIlluminatorStatus = common.MessageIlluminatorStatus
