//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Second GPS data.
type MessageGps2Raw = common.MessageGps2Raw
