//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Message with some status from autopilot to GCS about camera or antenna mount.
type MessageMountStatus = ardupilotmega.MessageMountStatus
