//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Read registers for a device.
type MessageDeviceOpRead = ardupilotmega.MessageDeviceOpRead
