//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/asluav"
)

// Fixed-wing soaring (i.e. thermal seeking) data
type MessageFwSoaringData = asluav.MessageFwSoaringData
