//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// PID tuning information.
type MessagePidTuning = ardupilotmega.MessagePidTuning
