//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/uavionix"
)

// Aircraft Registration.
type MessageUavionixAdsbOutCfgRegistration = uavionix.MessageUavionixAdsbOutCfgRegistration
