//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Request a current fence point from MAV.
type MessageFenceFetchPoint = ardupilotmega.MessageFenceFetchPoint
