//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Water depth
type MessageWaterDepth = ardupilotmega.MessageWaterDepth
