//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/development"
)

// Global position measurement or estimate.
type MessageGlobalPosition = development.MessageGlobalPosition
