//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/asluav"
)

// Send a command with up to seven parameters to the MAV and additional metadata
type MessageCommandLongStamped = asluav.MessageCommandLongStamped
