//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Accept / deny control of this MAV
type MessageChangeOperatorControlAck = common.MessageChangeOperatorControlAck
