//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/uavionix"
)

// Request messages.
type MessageUavionixAdsbGet = uavionix.MessageUavionixAdsbGet
