//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/icarous"
)

// Kinematic multi bands (track) output from Daidalus
type MessageIcarousKinematicBands = icarous.MessageIcarousKinematicBands
