//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// 3 axis gimbal measurements.
type MessageGimbalReport = ardupilotmega.MessageGimbalReport
