//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/avssuas"
)

// AVSS PRS system status.
type MessageAvssPrsSysStatus = avssuas.MessageAvssPrsSysStatus
