//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Camera Event.
type MessageCameraStatus = ardupilotmega.MessageCameraStatus
