//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/asluav"
)

// Monitoring of power board status
type MessageSensPowerBoard = asluav.MessageSensPowerBoard
