//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/development"
)

// The location of a target measured by MAV's onboard sensors.
type MessageTargetRelative = development.MessageTargetRelative
