//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Heartbeat from a HeroBus attached GoPro.
type MessageGoproHeartbeat = ardupilotmega.MessageGoproHeartbeat
