//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/uavionix"
)

// Dynamic data used to generate ADS-B out transponder data (send at 5Hz)
type MessageUavionixAdsbOutDynamic = uavionix.MessageUavionixAdsbOutDynamic
