//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/development"
)

// Information about key components of GNSS receivers, like signal authentication, interference and system errors.
type MessageGnssIntegrity = development.MessageGnssIntegrity
