//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/asluav"
)

// Extended EKF state estimates for ASLUAVs
type MessageEkfExt = asluav.MessageEkfExt
