//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Status of simulation environment, if used.
type MessageSimstate = ardupilotmega.MessageSimstate
