//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/stemstudios"
)

// Current LED State. Can be emitted by LED Strip Controller.
type MessageLedStripState = stemstudios.MessageLedStripState
