//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/asluav"
)

// Extended state information for ASLUAVs
type MessageAsluavStatus = asluav.MessageAsluavStatus
