//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Set the magnetometer offsets
type MessageSetMagOffsets = ardupilotmega.MessageSetMagOffsets
