//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/asluav"
)

// Status of the SatCom link
type MessageSatcomLinkStatus = asluav.MessageSatcomLinkStatus
