//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/pythonarraytest"
)

// Array test #3.
type MessageArrayTest_3 = pythonarraytest.MessageArrayTest_3
