//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/avssuas"
)

// Drone operation mode.
type MessageAvssDroneOperationMode = avssuas.MessageAvssDroneOperationMode
