//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/asluav"
)

// Maximum Power Point Tracker (MPPT) sensor data for solar module power performance tracking
type MessageSensMppt = asluav.MessageSensMppt
