//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/asluav"
)

// Calibrated airflow angle measurements
type MessageSensorAirflowAngles = asluav.MessageSensorAirflowAngles
