//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Reply from secure command.
type MessageSecureCommandReply = ardupilotmega.MessageSecureCommandReply
