//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// EKF Status message including flags and variances.
type MessageEkfStatusReport = ardupilotmega.MessageEkfStatusReport
