//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/asluav"
)

// Voltage and current sensor data
type MessageSensPower = asluav.MessageSensPower
