//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/development"
)

// Current motion information from sensors on a target
type MessageTargetAbsolute = development.MessageTargetAbsolute
