//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Reply to LOG_REQUEST_DATA
type MessageLogData = common.MessageLogData
