//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/development"
)

// Emitted during mission execution when control reaches MAV_CMD_GROUP_END.
type MessageGroupEnd = development.MessageGroupEnd
