//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/cubepilot"
)

// Herelink Telemetry
type MessageHerelinkTelem = cubepilot.MessageHerelinkTelem
