//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Vibration levels and accelerometer clipping
type MessageVibration = common.MessageVibration
