//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/test"
)

// Test all field types
type MessageTestTypes = test.MessageTestTypes
