//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/asluav"
)

// Off-board controls/commands for ASLUAVs
type MessageAslObctrl = asluav.MessageAslObctrl
