//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ualberta"
)

// System status specific to ualberta uav
type MessageUalbertaSysStatus = ualberta.MessageUalbertaSysStatus
