//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/cubepilot"
)

// Information about video stream
type MessageHerelinkVideoStreamInformation = cubepilot.MessageHerelinkVideoStreamInformation
