//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Camera-IMU triggering and synchronisation message.
type MessageCameraTrigger = common.MessageCameraTrigger
