//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/asluav"
)

// ASL-fixed-wing controller data
type MessageAslctrlData = asluav.MessageAslctrlData
