//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Status generated by radio and injected into MAVLink stream.
type MessageRadioStatus = common.MessageRadioStatus
