//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/asluav"
)

// Battery pack monitoring data for Li-Ion batteries
type MessageSensBatmon = asluav.MessageSensBatmon
