//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/pythonarraytest"
)

// Array test #8.
type MessageArrayTest_8 = pythonarraytest.MessageArrayTest_8
