//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/storm32"
)

// Information about the shot operation.
type MessageQshotStatus = storm32.MessageQshotStatus
