//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/storm32"
)

// Frsky SPort passthrough multi packet container.
type MessageFrskyPassthroughArray = storm32.MessageFrskyPassthroughArray
