//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/uavionix"
)

// Flight Identification for ADSB-Out vehicles.
type MessageUavionixAdsbOutCfgFlightid = uavionix.MessageUavionixAdsbOutCfgFlightid
