//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Status of simulation environment, if used
type MessageSimState = common.MessageSimState
