//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Camera vision based attitude and position deltas.
type MessageVisionPositionDelta = ardupilotmega.MessageVisionPositionDelta
