//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Response from a GOPRO_COMMAND set request.
type MessageGoproSetResponse = ardupilotmega.MessageGoproSetResponse
