//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/avssuas"
)

// Drone position.
type MessageAvssDronePosition = avssuas.MessageAvssDronePosition
