//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// The global position resulting from GPS and sensor fusion.
type MessageUtmGlobalPosition = common.MessageUtmGlobalPosition
