//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Data for injecting into the onboard GPS (used for DGPS)
type MessageGpsInjectData = common.MessageGpsInjectData
