//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Cumulative distance traveled for each reported wheel.
type MessageWheelDistance = common.MessageWheelDistance
