//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Status of geo-fencing. Sent in extended status stream when fencing enabled.
type MessageFenceStatus = common.MessageFenceStatus
