//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Request to control this MAV
type MessageChangeOperatorControl = common.MessageChangeOperatorControl
