//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Set the vehicle attitude and body angular rates.
type MessageActuatorControlTarget = common.MessageActuatorControlTarget
