//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Response from a PARAM_EXT_SET message.
type MessageParamExtAck = common.MessageParamExtAck
