//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Reply from secure command.
type MessageSecureCommandReply = ardupilotmega.MessageSecureCommandReply
