//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Wind estimation.
type MessageWind = ardupilotmega.MessageWind
