//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// State of autopilot RAM.
type MessageMeminfo = ardupilotmega.MessageMeminfo
