//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Read a configured an OSD parameter slot.
type MessageOsdParamShowConfig = ardupilotmega.MessageOsdParamShowConfig
