//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/cubepilot"
)

// offset response to encapsulated data.
type MessageCubepilotFirmwareUpdateResp = cubepilot.MessageCubepilotFirmwareUpdateResp
