//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/csairlink"
)

// Response to the authorization request
type MessageAirlinkAuthResponse = csairlink.MessageAirlinkAuthResponse
