//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Camera Capture Feedback.
type MessageCameraFeedback = ardupilotmega.MessageCameraFeedback
