//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/uavionix"
)

// Transceiver heartbeat with health report (updated every 10s)
type MessageUavionixAdsbTransceiverHealthReport = uavionix.MessageUavionixAdsbTransceiverHealthReport
