//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// 100 Hz gimbal torque command telemetry.
type MessageGimbalTorqueCmdReport = ardupilotmega.MessageGimbalTorqueCmdReport
