//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Read out the safety zone the MAV currently assumes.
type MessageSafetyAllowedArea = common.MessageSafetyAllowedArea
