//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Configure an OSD parameter slot.
type MessageOsdParamConfig = ardupilotmega.MessageOsdParamConfig
