//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// 2nd Battery status
type MessageBattery2 = ardupilotmega.MessageBattery2
