//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Data packet, size 96.
type MessageData96 = ardupilotmega.MessageData96
