//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Send a block of log data to remote location.
type MessageRemoteLogDataBlock = ardupilotmega.MessageRemoteLogDataBlock
