//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/cubepilot"
)

// Start firmware update with encapsulated data.
type MessageCubepilotFirmwareUpdateStart = cubepilot.MessageCubepilotFirmwareUpdateStart
