//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/uavionix"
)

// Flight Identification for ADSB-Out vehicles.
type MessageUavionixAdsbOutCfgFlightid = uavionix.MessageUavionixAdsbOutCfgFlightid
