//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Status of key hardware.
type MessageHwstatus = ardupilotmega.MessageHwstatus
