//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Provides state for additional features
type MessageExtendedSysState = common.MessageExtendedSysState
