//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Request to set a GOPRO_COMMAND with a desired.
type MessageGoproSetRequest = ardupilotmega.MessageGoproSetRequest
