//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/ardupilotmega"
)

// Send Status of each log block that autopilot board might have sent.
type MessageRemoteLogBlockStatus = ardupilotmega.MessageRemoteLogBlockStatus
