//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// RTCM message for injecting into the onboard GPS (used for DGPS)
type MessageGpsRtcmData = common.MessageGpsRtcmData
