//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Report button state change.
type MessageButtonChange = common.MessageButtonChange
