//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Orientation of a mount
type MessageMountOrientation = common.MessageMountOrientation
