//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Data stream status information.
type MessageDataStream = common.MessageDataStream
