//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Time/duration estimates for various events and actions given the current vehicle state and position.
type MessageTimeEstimateToTarget = common.MessageTimeEstimateToTarget
