//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Local position/attitude estimate from a vision source.
type MessageVisionPositionEstimate = common.MessageVisionPositionEstimate
