//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aircast-one/gomavlib/v3/pkg/dialects/common"
)

// Reply to LOG_REQUEST_LIST
type MessageLogEntry = common.MessageLogEntry
