//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aircast-one/gomavlib/v4/pkg/dialects/common"
)

// Information about a potential collision
type MessageCollision = common.MessageCollision
